### ISSUE TITLE
RenderArrow callback for treeNode

### ISSUE THREAD

**Issue by ddkwork** [Splizard/imgui#10]
hello you, how to set a callback for RenderArrow ?

**Comment by Splizard** [comment]
Since this is an immediate mode renderer, you can include callback logic when you detect the state changes from closed to open. If I understand correctly.

**Comment by ddkwork** [comment]
> 由于这是一个即时模式呈现器，因此在检测到状态从关闭更改为打开时，可以包含回调逻辑。如果我理解正确的话。

I'm sorry for my terrible English. I mean, can you make a callback function to draw the hierarchical expansion of the tree or close the triangle of the icon? Replace it with the circle I screenshotted. I've been looking at the drawing code for a long time and still can't understand how to get the correct coordinates of the hierarchical icons. You write a demo and I'll learn Xi your code, thank you.

**Comment by ddkwork** [comment]
> Since this is an immediate mode renderer, you can include callback logic when you detect the state changes from closed to open. If I understand correctly. 

https://github.com/ocornut/imgui/issues/6730
